service: eyedee

useDotenv: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(./serverless/custom.yml):custom}
provider: ${file(./serverless/provider.yml):provider}
resources:  ${file(./serverless/resources.yml):resources}
functions: ${file(./serverless/functions.yml):functions}
