TableUser:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:custom.stage}-user
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: username
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: index-username
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: 'ALL'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
TableMain:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:custom.stage}
    AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk # gsi-1-pk
        AttributeType: S
      - AttributeName: gsi-1-sk
        AttributeType: S
    KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: gsi-1
        KeySchema:
          - AttributeName: sk # gsi-1-pk
            KeyType: HASH
          - AttributeName: gsi-1-sk
            KeyType: RANGE
        Projection:
          ProjectionType: 'ALL'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
